[wokwi]
version = 1
firmware = 'config/.esphome/build/vent-axia-sentinel-kinetic/.pioenvs/vent-axia-sentinel-kinetic/firmware.factory.bin'
elf = 'config/.pioenvs/vent-axia-sentinel-kinetic/firmware.elf'