esphome:
  name: display-test

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  hardware_uart : UART0
  level: DEBUG
  logs:
    component: ERROR

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO2
  baud_rate: 9600

external_components:
  - source: components #Make sure there is a folder named components/vent_axia_sentinel_kinetic at the same location as this YAML

vent_axia_sentinel_kinetic:
  # id: vent_axia_sentinel_kinetic

binary_sensor:
  - platform: vent_axia_sentinel_kinetic
    has_target:
      name: Presence

sensor:
  - platform: vent_axia_sentinel_kinetic
    light:
      name: light

switch:
  - platform: vent_axia_sentinel_kinetic
    up:
      name: "control up"
    down:
      name: "control down"
    set:
      name: "control set"
    main:
      name: "control main"

number:
  - platform: vent_axia_sentinel_kinetic
    timeout:
      name: timeout

button:
  - platform: vent_axia_sentinel_kinetic
    # up_button:
    #   name: "Up Button"
    # down_button:
    #   name: "Down Button"
    factory_reset:
      name: "factory reset"

text_sensor:
  - platform: vent_axia_sentinel_kinetic
    version:
      name: "firmware version"

select:
  - platform: vent_axia_sentinel_kinetic
    distance_resolution:
      name: "distance resolution"