esphome:
  name: display-test

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  hardware_uart : UART0
  level: VERBOSE
  logs:
    component: ERROR

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO2
  baud_rate: 9600

external_components:
  - source: components #Make sure there is a folder named components/vent_axia_sentinel_kinetic at the same location as this YAML

vent_axia_sentinel_kinetic:

switch:
  - platform: vent_axia_sentinel_kinetic
    up:
      name: "Up Switch"
      id: sw_up
    down:
      name: "Down Switch"
      id: sw_down
    set:
      name: "Set Switch"
      id: sw_set
    main:
      name: "Main Switch"
      id: sw_main

binary_sensor:
  - platform: gpio
    id: bit0
    pin:
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bit 0 (LSB)"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.turn_on: sw_up
    on_release:
      - switch.turn_off: sw_up
  - platform: gpio
    id: bit1
    pin:
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bit 1"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.turn_on: sw_down
    on_release:
      - switch.turn_off: sw_down
  - platform: gpio
    id: bit2
    pin:
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bit 2"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.turn_on: sw_set
    on_release:
      - switch.turn_off: sw_set
  - platform: gpio
    id: bit3
    pin:
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bit 3 (MSB)"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - switch.turn_on: sw_main
    on_release:
      - switch.turn_off: sw_main