esphome:
  name: esphome-web-590119
  friendly_name: DC Power Logger
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# # Example configuration entry
# uart:
#   tx_pin: D1
#   rx_pin: D2
#   baud_rate: 9600
#   data_bits: 8
#   stop_bits: 2
#   parity: NONE
  

# sensor:
#   - platform: uptime
#     name: "PZEM-017 uptime"
#     update_interval: 30s
#   - platform: wifi_signal
#     name: "PZEM-017 WiFi Signal Sensor"
#     update_interval: 30s
#   - platform: pzemdc
#     address: 30
#     current:
#       name: "PZEM-017 Current"
#     voltage:
#       name: "PZEM-017 Voltage"
#     power:
#       name: "PZEM-017 Power"
#     energy:
#       name: "PZEM-017 Energy"
#     update_interval: 60s

i2c:
  sda: GPIO4  # D2 on Wemos
  scl: GPIO5  # D1 on Wemos
  scan: true

sensor:
  - platform: adc
    pin: A0
    name: "Windspeed"
    id: windspeed_sensor
    unit_of_measurement: "km/h"
    accuracy_decimals: 2
    update_interval: 1s
    filters:
      - multiply: 30
    #   - calibrate_linear:
    #       - 0.41572 -> 0.0
    #       - 2.0 -> 116

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27  # Verify with I2C scan
    update_interval: 1s
    lambda: |-
      it.printf(0, 0, "Wind: %.2f km/h", id(windspeed_sensor).state);
      // it.printf(0, 0, "HELLO WORLD");