esphome:
  name: display-test

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  hardware_uart : UART0
  level: VERBOSE
  logs:
    component: ERROR

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO2
  baud_rate: 9600

# External component for UART data processing
external_components:
  - source: components

uartex:

text_sensor:
  # Raw string from UART (read once)
  - platform: uartex
    name: LCD_RAW
    id: "lcd_raw"
    lambda: 'return std::string(reinterpret_cast<const char*>(data + 5), 33);'