esphome:
  friendly_name: VentAxia Controller 2
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.f_cpu: 160000000L #increase clock speed

esp8266:
  board: d1_mini  # Adjust to your specific ESP8266 board
  # framework:
  #   type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_pass

# WiFi credentials
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot if WiFi connection fails
  ap:
    ssid: "Ventaxia Fallback"
    password: !secret fallback_password

captive_portal:

# # Enable logging
logger:
  # level: NONE #Dissable logs on UART
  level: DEBUG
  # deassert_rts_dtr: true
  # hardware_uart : UART0 
  baud_rate: 0
  logs:
    component: ERROR

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  id: demo_uart

i2c:
  sda: 4
  scl: 5
  scan: false

packages:
  common: !include common.yaml