substitutions:
  ext_comp_repo_ref: develop

external_components:
  - source:
      type: git
      url: https://github.com/FutureProofHomes/Satellite1-ESPHome
      ref: ${ext_comp_repo_ref}
    components: [ i2s_audio, satellite1, memory_flasher, tas2780, pcm5122, fusb302b ]
