esphome:
  platformio_options:
    board_build.flash_mode: dio
    board_upload.maximum_size: 16777216
      
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      
      # FreeRTOS
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      
      # LWIP
      #CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY: "n"
      #CONFIG_LWIP_TCPIP_TASK_AFFINITY_CPU1: "y"
      
      #CONFIG_LWIP_TCP_MSS: "1460"
      CONFIG_LWIP_TCP_WND_DEFAULT: "23360"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      
      CONFIG_LWIP_TCPIP_RECVMBOX_SIZE: "32"
      CONFIG_LWIP_TCP_RECVMBOX_SIZE: "18"
      #CONFIG_LWIP_UDP_RECVMBOX_SIZE: "6"
      
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
      
      CONFIG_TCP_QUEUE_OOSEQ: "y"
      CONFIG_TCP_OVERSIZE_MSS: "y"
      CONFIG_LWIP_WND_SCALE: "y"
      CONFIG_TCP_RCV_SCALE: "3"
      
      #CONFIG_ESP32_WIFI_RX_BA_WIN: "32" # = min(2*STATIC_RX_BUFFER_NUM, DYNAMIC_RX_BUFFER_NUM)
      
      # BT
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: i2c_0
    sda: GPIO5
    scl: GPIO6
    frequency: 400kHz
    scan: True

spi:
  - id: spi_0
    clk_pin:  GPIO12
    mosi_pin: GPIO11
    miso_pin: GPIO13
    interface: SPI2

i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO07
    i2s_bclk_pin: GPIO08
    i2s_mclk_pin: GPIO16
    access_mode: duplex
